# Generated by Django 3.1.13 on 2021-10-27 10:35

import api_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField()),
                ('category', models.CharField(choices=[('mobiles', 'Mobiles'), ('smartphones', 'Smart Phones'), ('accessories', 'Accessories')], max_length=50)),
                ('date_first_available', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=api_app.models.nameFile)),
            ],
        ),
    ]
